apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-server
  labels:
    app: simulation-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation-server
  template:
    metadata:
      labels:
        app: simulation-server
    spec:
      containers:
      - name: simulation-server
        image: simulation-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: simulation-server-service
spec:
  selector:
    app: simulation-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 